### ISSUE TITLE
bang, databasenya kalo buat qbox ga gada owner id nya, kayanya bukan pake idintifier deh, tapi pake citizenid

### ISSUE THREAD

**Issue by Apriawanto15** [tasiuskenways/ts_locker#4]
terusss, coba convert ke qbox kalo ada waktu, tadi eror di input gitu, terus kalo bisa pake sistem bisa dua sewa gudang soalnya kalo udah sewa disewa lagi bentrok, terus kalo udah sewa menu sewanya bisa hilang, saran aja ini mah ya, semoga sukses bang lancar2 
![image](https://github.com/tasiuskenways/uus-gudang/assets/58946086/7a6edd02-9058-4b80-8a8e-f4b56585faa2)

**Comment by tasiuskenways** [comment]
Noted mas. Bakal Di Fix Dan Kemungkinan Bakal Banyak Refactor

**Comment by tasiuskenways** [comment]
V2 udah release ya @Apriawanto15 bug tsb sudah di fix, jika nemu bug lagi silahkan ajuin di discord yg tertera di readme nya yakk!!. Thankyouu!!
